- name: Create RHBK federation
  ansible.builtin.import_tasks: rhbk_setup_idp.yml
  when: state == "present"

- name: Delete RHBK federation
  ansible.builtin.import_tasks: rhbk_remove_idp.yml
  when: state == "absent"
