- name: Login to RHBK and get admin token
  ansible.builtin.uri:
    url: "https://{{ rhbk_host }}/realms/master/protocol/openid-connect/token"
    method: POST
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    body_format: form-urlencoded
    body:
      grant_type: password
      client_id: admin-cli
      username: "{{ rhbk_admin_user }}"
      password: "{{ rhbk_admin_password }}"
    validate_certs: "{{ rhbk_verify_ssl }}"
    return_content: true
  register: rhbk_auth

- name: Get LDAP Federation Component list
  ansible.builtin.uri:
    url: "https://{{ rhbk_host }}/admin/realms/{{ rhbk_realm }}/components?type=org.keycloak.storage.UserStorageProvider"
    method: GET
    headers:
      Authorization: "Bearer {{ rhbk_auth.json.access_token }}"
    return_content: true
    validate_certs: "{{ rhbk_verify_ssl }}"
  register: ldap_components

- name: Extract LDAP federation component ({{ rhbk_federation_name }})
  ansible.builtin.set_fact:
    idm_component_obj: >-
      {{
        ldap_components.json
        | selectattr('name', 'equalto', rhbk_federation_name)
        | list
        | first | default({})
      }}
  when: ldap_components.json is defined

- name: Set the ldap_component_id
  ansible.builtin.set_fact:
    ldap_component_id: "{{ idm_component_obj.id | default('') }}"

- name: Show the extracted component ID
  ansible.builtin.debug:
    msg: "LDAP component ID: {{ ldap_component_id }}"

- name: Get all existing LDAP mappers for component
  ansible.builtin.uri:
    url: "https://{{ rhbk_host }}/admin/realms/{{ rhbk_realm }}/components?parent={{ ldap_component_id }}&type=org.keycloak.storage.ldap.mappers.LDAPStorageMapper"
    method: GET
    headers:
      Authorization: "Bearer {{ rhbk_auth.json.access_token }}"
    return_content: true
    validate_certs: "{{ rhbk_verify_ssl }}"
  register: ldap_mappers
  when: ldap_component_id != ""

- name: Check if ldap-group-mapper2 already exists
  ansible.builtin.set_fact:
    ldap_group_mapper_exists: >-
      {{
        ldap_mappers.json
        | selectattr('name', 'equalto', 'ldap-group-mapper2')
        | list | length > 0
      }}
  when: ldap_mappers.json is defined

- name: Create LDAP Group Mapper
  ansible.builtin.uri:
    url: "https://{{ rhbk_host }}/admin/realms/{{ rhbk_realm }}/components"
    method: POST
    headers:
      Authorization: "Bearer {{ rhbk_auth.json.access_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      name: "ldap-group-mapper2"
      parentId: "{{ ldap_component_id }}"
      providerId: "group-ldap-mapper"
      providerType: "org.keycloak.storage.ldap.mappers.LDAPStorageMapper"
      config: "{{ ldap_group_config }}"
    validate_certs: "{{ rhbk_verify_ssl }}"
    status_code: 201
  when:
    - ldap_group_mapper_exists is defined
    - not ldap_group_mapper_exists

